#pragma config(Sensor, dgtl1,  firstPin,       sensorQuadEncoder)
#pragma config(Motor,  port1,           dootleft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           dootright,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int wheelRad=5.1;

int goStraight(){
	int ticksInitial=SensorValue[firstPin];
	int ticksPassed=0;
	motor[dootleft]=127;
	motor[dootright]=127;
	sleep(10);
	ticksPassed=SensorValue[firstPin]-ticksInitial;

	return ticksPassed;
}

task main()
{
	int sideTraversed;
	sideTraversed+=(goStraight()*392/(2*PI*wheelRad));
	if(sideTraversed>=50){

	}


}
